title: Michael Xing
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://michael-xing.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 6

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Michael-Xing
   twitter: Michael-Xing
   facebook: Michael-Xing
   email: haitaox2013@gmail.com

google_analytics: "UA-83696535-1"
